<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Polynomial\\' => array($baseDir . '/src/polynomial'),
    'Matrix\\' => array($baseDir . '/src/matrix'),
    'App\\' => array($baseDir . '/src/app'),
);
